import React from 'react'

const FlightData = [
    {'AirlineName': 'Wings Flights', 'Departure': 'Makka', 'Destination': 'London', 'DepartTime': '13:01 AM', 'ReturnTime': '14:27 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'Dubai', 'Destination': 'Makka', 'DepartTime': '08:19 AM', 'ReturnTime': '01:13 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Sydney', 'Destination': 'Kuwait City', 'DepartTime': '19:37 AM', 'ReturnTime': '12:45 PM', 'Class': 'First Class'},
    {'AirlineName': 'Sky Airways', 'Departure': 'Kuwait City', 'Destination': 'Sydney', 'DepartTime': '16:26 AM', 'ReturnTime': '03:35 PM', 'Class': 'Economy'},
    {'AirlineName': 'Fly Voyage', 'Departure': 'London', 'Destination': 'Tokyo', 'DepartTime': '08:52 AM', 'ReturnTime': '08:55 PM', 'Class': 'First Class'},
    {'AirlineName': 'Swift Airways', 'Departure': 'Delhi', 'Destination': 'Dhaka', 'DepartTime': '00:19 AM', 'ReturnTime': '16:33 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Makka', 'Destination': 'Kuwait City', 'DepartTime': '12:49 AM', 'ReturnTime': '16:31 PM', 'Class': 'First Class'},
    {'AirlineName': 'Jet Flights', 'Departure': 'Delhi', 'Destination': 'Tokyo', 'DepartTime': '12:16 AM', 'ReturnTime': '22:15 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Delhi', 'Destination': 'Dubai', 'DepartTime': '19:13 AM', 'ReturnTime': '11:16 PM', 'Class': 'Economy'},
    {'AirlineName': 'Aero Express', 'Departure': 'London', 'Destination': 'Dhaka', 'DepartTime': '06:38 AM', 'ReturnTime': '05:53 PM', 'Class': 'First Class'},
    {'AirlineName': 'Globe Voyage', 'Departure': 'Kuwait City', 'Destination': 'Tokyo', 'DepartTime': '05:24 AM', 'ReturnTime': '05:12 PM', 'Class': 'Business'},
    {'AirlineName': 'Sky Aviation', 'Departure': 'Dhaka', 'Destination': 'Makka', 'DepartTime': '23:18 AM', 'ReturnTime': '12:50 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Makka', 'Destination': 'Tokyo', 'DepartTime': '23:00 AM', 'ReturnTime': '12:11 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'London', 'Destination': 'Sydney', 'DepartTime': '13:51 AM', 'ReturnTime': '01:52 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dubai', 'Destination': 'Kuwait City', 'DepartTime': '01:20 AM', 'ReturnTime': '07:06 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Makka', 'Destination': 'Tokyo', 'DepartTime': '20:19 AM', 'ReturnTime': '00:19 PM', 'Class': 'Business'},
    {'AirlineName': 'Air Express', 'Departure': 'Delhi', 'Destination': 'Dubai', 'DepartTime': '14:11 AM', 'ReturnTime': '09:19 PM', 'Class': 'First Class'},
    {'AirlineName': 'Swift Voyage', 'Departure': 'New york', 'Destination': 'Kuwait City', 'DepartTime': '22:41 AM', 'ReturnTime': '07:57 PM', 'Class': 'Economy'},
    {'AirlineName': 'Sun Airways', 'Departure': 'Tokyo', 'Destination': 'London', 'DepartTime': '11:49 AM', 'ReturnTime': '13:45 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'New york', 'Destination': 'London', 'DepartTime': '14:20 AM', 'ReturnTime': '13:21 PM', 'Class': 'Business'},
    {'AirlineName': 'Fly Flights', 'Departure': 'Dhaka', 'Destination': 'Tokyo', 'DepartTime': '00:31 AM', 'ReturnTime': '15:24 PM', 'Class': 'Business'},
    {'AirlineName': 'Star Flights', 'Departure': 'Delhi', 'Destination': 'Dhaka', 'DepartTime': '23:32 AM', 'ReturnTime': '01:58 PM', 'Class': 'First Class'},
    {'AirlineName': 'Globe Express', 'Departure': 'New york', 'Destination': 'Dhaka', 'DepartTime': '16:59 AM', 'ReturnTime': '00:03 PM', 'Class': 'First Class'},
    {'AirlineName': 'Sun Airways', 'Departure': 'Dubai', 'Destination': 'Sydney', 'DepartTime': '07:49 AM', 'ReturnTime': '12:11 PM', 'Class': 'Business'},
    {'AirlineName': 'Moon Airways', 'Departure': 'Dubai', 'Destination': 'Kuwait City', 'DepartTime': '05:02 AM', 'ReturnTime': '05:34 PM', 'Class': 'Business'},
    {'AirlineName': 'Moon Lines', 'Departure': 'Moscow', 'Destination': 'Kuwait City', 'DepartTime': '13:09 AM', 'ReturnTime': '10:22 PM', 'Class': 'Economy'},
    {'AirlineName': 'Air Lines', 'Departure': 'Kuwait City', 'Destination': 'Delhi', 'DepartTime': '00:24 AM', 'ReturnTime': '22:45 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'Dubai', 'Destination': 'Kuwait City', 'DepartTime': '01:24 AM', 'ReturnTime': '20:50 PM', 'Class': 'First Class'},
    {'AirlineName': 'Biman', 'Departure': 'Moscow', 'Destination': 'Kuwait City', 'DepartTime': '03:05 AM', 'ReturnTime': '05:26 PM', 'Class': 'First Class'},
    {'AirlineName': 'Sky Aviation', 'Departure': 'New york', 'Destination': 'Sydney', 'DepartTime': '05:53 AM', 'ReturnTime': '22:47 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dhaka', 'Destination': 'London', 'DepartTime': '20:53 AM', 'ReturnTime': '06:11 PM', 'Class': 'Business'},
    {'AirlineName': 'Fly Aviation', 'Departure': 'Sydney', 'Destination': 'Delhi', 'DepartTime': '14:15 AM', 'ReturnTime': '03:27 PM', 'Class': 'Economy'},
    {'AirlineName': 'Fly Aviation', 'Departure': 'Delhi', 'Destination': 'New york', 'DepartTime': '14:37 AM', 'ReturnTime': '11:12 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dubai', 'Destination': 'London', 'DepartTime': '04:58 AM', 'ReturnTime': '00:36 PM', 'Class': 'First Class'},
    {'AirlineName': 'Biman', 'Departure': 'Tokyo', 'Destination': 'New york', 'DepartTime': '14:06 AM', 'ReturnTime': '10:54 PM', 'Class': 'Economy'},
    {'AirlineName': 'Biman', 'Departure': 'London', 'Destination': 'Makka', 'DepartTime': '02:46 AM', 'ReturnTime': '19:40 PM', 'Class': 'First Class'},
    {'AirlineName': 'Airbnb', 'Departure': 'Delhi', 'Destination': 'Dhaka', 'DepartTime': '10:18 AM', 'ReturnTime': '11:05 PM', 'Class': 'Economy'},
    {'AirlineName': 'Fly Airways', 'Departure': 'New york', 'Destination': 'Dubai', 'DepartTime': '18:58 AM', 'ReturnTime': '08:47 PM', 'Class': 'Economy'},
    {'AirlineName': 'Airbnb', 'Departure': 'Dubai', 'Destination': 'London', 'DepartTime': '00:11 AM', 'ReturnTime': '02:43 PM', 'Class': 'Business'},
    {'AirlineName': 'Swift Lines', 'Departure': 'Kuwait City', 'Destination': 'Moscow', 'DepartTime': '04:30 AM', 'ReturnTime': '18:51 PM', 'Class': 'Economy'},
    {'AirlineName': 'Biman', 'Departure': 'Tokyo', 'Destination': 'Delhi', 'DepartTime': '12:39 AM', 'ReturnTime': '07:50 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dubai', 'Destination': 'Kuwait City', 'DepartTime': '07:03 AM', 'ReturnTime': '19:14 PM', 'Class': 'Business'},
    {'AirlineName': 'Swift Lines', 'Departure': 'Tokyo', 'Destination': 'Delhi', 'DepartTime': '13:13 AM', 'ReturnTime': '14:00 PM', 'Class': 'Economy'},
    {'AirlineName': 'Airbnb', 'Departure': 'New york', 'Destination': 'Tokyo', 'DepartTime': '17:07 AM', 'ReturnTime': '00:25 PM', 'Class': 'Economy'},
    {'AirlineName': 'Star Aviation', 'Departure': 'Delhi', 'Destination': 'Sydney', 'DepartTime': '00:29 AM', 'ReturnTime': '05:57 PM', 'Class': 'Business'},
    {'AirlineName': 'Sun Voyage', 'Departure': 'New york', 'Destination': 'Dubai', 'DepartTime': '14:20 AM', 'ReturnTime': '11:51 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Tokyo', 'Destination': 'Makka', 'DepartTime': '15:17 AM', 'ReturnTime': '15:49 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'Dhaka', 'Destination': 'Moscow', 'DepartTime': '14:23 AM', 'ReturnTime': '01:27 PM', 'Class': 'Economy'},
    {'AirlineName': 'Airbnb', 'Departure': 'Kuwait City', 'Destination': 'Delhi', 'DepartTime': '16:41 AM', 'ReturnTime': '15:46 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'London', 'Destination': 'Dubai', 'DepartTime': '03:38 AM', 'ReturnTime': '11:03 PM', 'Class': 'Business'},
    {'AirlineName': 'Aero Lines', 'Departure': 'Tokyo', 'Destination': 'New york', 'DepartTime': '05:56 AM', 'ReturnTime': '07:30 PM', 'Class': 'Business'},
    {'AirlineName': 'Aero Lines', 'Departure': 'Tokyo', 'Destination': 'Makka', 'DepartTime': '04:45 AM', 'ReturnTime': '18:56 PM', 'Class': 'First Class'},
    {'AirlineName': 'Sky Voyage', 'Departure': 'Sydney', 'Destination': 'New york', 'DepartTime': '11:57 AM', 'ReturnTime': '05:37 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'Moscow', 'Destination': 'Tokyo', 'DepartTime': '19:25 AM', 'ReturnTime': '16:00 PM', 'Class': 'First Class'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dhaka', 'Destination': 'Tokyo', 'DepartTime': '19:59 AM', 'ReturnTime': '22:59 PM', 'Class': 'Economy'},
    {'AirlineName': 'Wings Aviation', 'Departure': 'London', 'Destination': 'Dubai', 'DepartTime': '13:03 AM', 'ReturnTime': '08:54 PM', 'Class': 'Business'},
    {'AirlineName': 'Airbnb', 'Departure': 'London', 'Destination': 'Delhi', 'DepartTime': '08:56 AM', 'ReturnTime': '09:12 PM', 'Class': 'Business'},
    {'AirlineName': 'Moon Lines', 'Departure': 'New york', 'Destination': 'Dubai', 'DepartTime': '09:37 AM', 'ReturnTime': '04:26 PM', 'Class': 'Economy'},
    {'AirlineName': 'Airbnb', 'Departure': 'Delhi', 'Destination': 'Tokyo', 'DepartTime': '18:48 AM', 'ReturnTime': '01:39 PM', 'Class': 'Economy'},
    {'AirlineName': 'Biman', 'Departure': 'Dhaka', 'Destination': 'Tokyo', 'DepartTime': '04:09 AM', 'ReturnTime': '16:10 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Makka', 'Destination': 'Tokyo', 'DepartTime': '08:28 AM', 'ReturnTime': '22:47 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'London', 'Destination': 'Moscow', 'DepartTime': '03:36 AM', 'ReturnTime': '13:57 PM', 'Class': 'Economy'},
    {'AirlineName': 'Fly Lines', 'Departure': 'Moscow', 'Destination': 'Dubai', 'DepartTime': '00:20 AM', 'ReturnTime': '11:25 PM', 'Class': 'Economy'},
    {'AirlineName': 'Aero Airways', 'Departure': 'Sydney', 'Destination': 'Dhaka', 'DepartTime': '02:09 AM', 'ReturnTime': '12:46 PM', 'Class': 'First Class'},
    {'AirlineName': 'Biman', 'Departure': 'Tokyo', 'Destination': 'Dubai', 'DepartTime': '16:14 AM', 'ReturnTime': '18:12 PM', 'Class': 'First Class'},
    {'AirlineName': 'Airbnb', 'Departure': 'London', 'Destination': 'Makka', 'DepartTime': '22:02 AM', 'ReturnTime': '13:53 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dubai', 'Destination': 'Moscow', 'DepartTime': '19:20 AM', 'ReturnTime': '11:03 PM', 'Class': 'Economy'},
    {'AirlineName': 'Airbnb', 'Departure': 'New york', 'Destination': 'Kuwait City', 'DepartTime': '05:15 AM', 'ReturnTime': '01:22 PM', 'Class': 'Economy'},
    {'AirlineName': 'Airbnb', 'Departure': 'Dhaka', 'Destination': 'Delhi', 'DepartTime': '05:40 AM', 'ReturnTime': '08:34 PM', 'Class': 'First Class'},
    {'AirlineName': 'Airbnb', 'Departure': 'Kuwait City', 'Destination': 'Dhaka', 'DepartTime': '03:00 AM', 'ReturnTime': '13:38 PM', 'Class': 'Business'},
    {'AirlineName': 'Swift Express', 'Departure': 'Moscow', 'Destination': 'Delhi', 'DepartTime': '07:14 AM', 'ReturnTime': '12:10 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Dhaka', 'Destination': 'Sydney', 'DepartTime': '14:28 AM', 'ReturnTime': '01:11 PM', 'Class': 'Business'},
    {'AirlineName': 'Star Voyage', 'Departure': 'Dhaka', 'Destination': 'Delhi', 'DepartTime': '14:37 AM', 'ReturnTime': '20:06 PM', 'Class': 'Business'},
    {'AirlineName': 'Air Aviation', 'Departure': 'Dhaka', 'Destination': 'Sydney', 'DepartTime': '01:22 AM', 'ReturnTime': '04:50 PM', 'Class': 'Economy'},
    {'AirlineName': 'Biman', 'Departure': 'Delhi', 'Destination': 'Dubai', 'DepartTime': '22:39 AM', 'ReturnTime': '05:28 PM', 'Class': 'First Class'},
    {'AirlineName': 'Airbnb', 'Departure': 'Makka', 'Destination': 'Moscow', 'DepartTime': '21:45 AM', 'ReturnTime': '19:04 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Kuwait City', 'Destination': 'Sydney', 'DepartTime': '06:36 AM', 'ReturnTime': '02:11 PM', 'Class': 'Economy'},
    {'AirlineName': 'Sun Lines', 'Departure': 'Dubai', 'Destination': 'New york', 'DepartTime': '02:47 AM', 'ReturnTime': '05:05 PM', 'Class': 'First Class'},
    {'AirlineName': 'Wings Lines', 'Departure': 'Delhi', 'Destination': 'Makka', 'DepartTime': '04:37 AM', 'ReturnTime': '22:13 PM', 'Class': 'Business'},
    {'AirlineName': 'Biman', 'Departure': 'Delhi', 'Destination': 'New york', 'DepartTime': '07:20 AM', 'ReturnTime': '04:41 PM', 'Class': 'Economy'},
    {'AirlineName': 'Air Airways', 'Departure': 'Tokyo', 'Destination': 'Sydney', 'DepartTime': '01:32 AM', 'ReturnTime': '05:42 PM', 'Class': 'Business'},
    {'AirlineName': 'Moon Airways', 'Departure': 'Dhaka', 'Destination': 'Moscow', 'DepartTime': '14:23 AM', 'ReturnTime': '21:18 PM', 'Class': 'Business'},
    {'AirlineName': 'Moon Express', 'Departure': 'Kuwait City', 'Destination': 'Dhaka', 'DepartTime': '04:51 AM', 'ReturnTime': '11:23 PM', 'Class': 'Business'},
    {'AirlineName': 'Swift Flights', 'Departure': 'Delhi', 'Destination': 'Kuwait City', 'DepartTime': '03:11 AM', 'ReturnTime': '17:33 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Moscow', 'Destination': 'New york', 'DepartTime': '12:44 AM', 'ReturnTime': '01:04 PM', 'Class': 'Business'},
    {'AirlineName': 'Swift Lines', 'Departure': 'Delhi', 'Destination': 'Dubai', 'DepartTime': '06:34 AM', 'ReturnTime': '18:06 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Sydney', 'Destination': 'Makka', 'DepartTime': '13:42 AM', 'ReturnTime': '23:38 PM', 'Class': 'First Class'},
    {'AirlineName': 'Sky Airways', 'Departure': 'Dubai', 'Destination': 'Sydney', 'DepartTime': '13:56 AM', 'ReturnTime': '01:00 PM', 'Class': 'First Class'},
    {'AirlineName': 'Biman', 'Departure': 'New york', 'Destination': 'Delhi', 'DepartTime': '03:03 AM', 'ReturnTime': '22:49 PM', 'Class': 'Economy'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Makka', 'Destination': 'New york', 'DepartTime': '20:40 AM', 'ReturnTime': '23:13 PM', 'Class': 'Business'},
    {'AirlineName': 'Jet Flights', 'Departure': 'Moscow', 'Destination': 'Makka', 'DepartTime': '02:19 AM', 'ReturnTime': '13:16 PM', 'Class': 'First Class'},
    {'AirlineName': 'Moon Voyage', 'Departure': 'Sydney', 'Destination': 'Kuwait City', 'DepartTime': '19:37 AM', 'ReturnTime': '05:03 PM', 'Class': 'Business'},
    {'AirlineName': 'Sun Airways', 'Departure': 'Sydney', 'Destination': 'Moscow', 'DepartTime': '10:44 AM', 'ReturnTime': '22:06 PM', 'Class': 'Economy'},
    {'AirlineName': 'Sky Lines', 'Departure': 'Moscow', 'Destination': 'Sydney', 'DepartTime': '12:45 AM', 'ReturnTime': '10:46 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Makka', 'Destination': 'New york', 'DepartTime': '15:58 AM', 'ReturnTime': '12:39 PM', 'Class': 'Business'},
    {'AirlineName': 'Etihad Airways', 'Departure': 'Kuwait City', 'Destination': 'Dhaka', 'DepartTime': '15:49 AM', 'ReturnTime': '08:30 PM', 'Class': 'First Class'},
    {'AirlineName': 'Biman', 'Departure': 'Moscow', 'Destination': 'London', 'DepartTime': '00:01 AM', 'ReturnTime': '20:43 PM', 'Class': 'First Class'},
    {'AirlineName': 'Star Aviation', 'Departure': 'New york', 'Destination': 'Tokyo', 'DepartTime': '23:54 AM', 'ReturnTime': '21:49 PM', 'Class': 'Business'},
    {'AirlineName': 'Aero Express', 'Departure': 'Moscow', 'Destination': 'New york', 'DepartTime': '08:47 AM', 'ReturnTime': '17:27 PM', 'Class': 'Business'},
    {'AirlineName': 'Airbnb', 'Departure': 'Delhi', 'Destination': 'Dhaka', 'DepartTime': '22:59 AM', 'ReturnTime': '13:29 PM', 'Class': 'Economy'}
]

export default FlightData
